export const RENDER_STATE = 'RENDER_STATE';

export const MOVE_CIRCLE = 'MOVE_CIRCLE';
export const MOVE_CIRCLE_ABSOLUTE = 'MOVE_CIRCLE_ABSOLUTE';

export const CHANGE_MOVEMENT_DIRECTION = 'CHANGE_MOVEMENT_DIRECTION';
export const CHANGE_MOVEMENT_VELOCITY = 'CHANGE_MOVEMENT_VELOCITY';
